name: CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress
            --exclude 'localhost'
            --exclude 'linkedin\.com'
            --exclude 'storage\.googleapis\.com'
            --exclude 'viewer\.imaging\.datacommons\.cancer\.gov'
            --exclude 'dx\.doi\.org'
            '**/*.md'
            '**/*.py'
            '**/*.rst'
            '**/*.html'
          fail: true
